# Generated by Django 4.1 on 2022-09-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewTable",
            fields=[
                ("uuid", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.CharField(blank=True, max_length=30, null=True)),
                ("name", models.CharField(blank=True, max_length=15, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "new_table", "managed": False,},
        ),
    ]
