# Generated by Django 4.1.3 on 2022-11-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_dropbox_delete_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropbox",
            name="document",
            field=models.FileField(max_length=200, upload_to=""),
        ),
        migrations.AlterField(
            model_name="dropbox",
            name="title",
            field=models.CharField(editable=False, max_length=36),
        ),
    ]
